version: "3.3"

services:
  # node-app:
  #   env_file:
  #     - .env
  #   restart: always
  #   depends_on:
  #     - mysql
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:${PORT}
  #   environment:
  #     PORT: ${PORT}
  #     DATABASE_URL: ${DATABASE_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #   networks:
  #     - bhojan-network

  postgres:
    container_name: postgres
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      - bhojan-network

networks:
  bhojan-network:
    driver: bridge

volumes:
  postgres_data:
